const Data = {
    products : [
         {
             _id :'1' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'10',
             category : 'shirts',
             image : 'image/img2.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'2' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'20',
             category : 'shirts',
             image : 'image/img4.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'3' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'9',
             category : 'shirts',
             image : 'image/img4.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'4' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'17',
             category : 'shirts',
             image : 'image/img5.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'5' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'7',
             category : 'shirts',
             image : 'image/img6.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'6' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'5',
             category : 'shirts',
             image : 'image/img2.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'7' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'12',
             category : 'shirts',
             image : 'image/img6.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         },
         {
             _id :'8' ,
             name : 'Nike Slim Shirts',
             price : '120',
             countInStock:'15',
             category : 'shirts',
             image : 'image/img6.jpg',
             brand : 'Nike',
             numReviews : '10',
             ratings : '4.6',
             description : 'high quality shirts',
 
         }, {
            _id :'9' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'10',
            category : 'shirts',
            image : 'image/img2.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'10' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'20',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'11' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'9',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'12' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'17',
            category : 'shirts',
            image : 'image/img5.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'13' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'7',
            category : 'shirts',
            image : 'image/img6.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'14' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'5',
            category : 'shirts',
            image : 'image/img6.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'15' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'12',
            category : 'shirts',
            image : 'image/img6.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'16' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'15',
            category : 'shirts',
            image : 'image/img6.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },,
        {
            _id :'17' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'12',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
        {
            _id :'18' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'15',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        }, {
            _id :'19' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'15',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        }, {
            _id :'20' ,
            name : 'Nike Slim Shirts',
            price : '120',
            countInStock:'15',
            category : 'shirts',
            image : 'image/img4.jpg',
            brand : 'Nike',
            numReviews : '10',
            ratings : '4.6',
            description : 'high quality shirts',

        },
       
        
     ]
 }
 export default Data;